### ISSUE TITLE
cue application on exome

### ISSUE THREAD

**Issue by marcelamtrucco** [PopicLab/cue#19]
Hello,

I would like to check if CUE can be applied to analysis data from Exome sequencing? Thanks

**Comment by viq854** [comment]
Hi @marcelamtrucco , 

Yes, the framework can be applied to the analysis of exome data as well -- since the SV signals will similarly appear in exome-based images. However, we haven't yet created models trained on exome data specifically (the WGS models cannot be applied directly). The framework includes support for training custom models and generating training data, which can be used to specialize the models to WES. 
Support for WES inputs is on our roadmap though and I can let you know when we have such models released. 

Cheers,
V
